services:
  web:
    image: nginx:latest
    ports:
      - "443:443" # https
    volumes:
        # página html
      - ./html:/usr/share/nginx/html

        # configuração do servidor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

        # certificados
      - ./certs/server.crt:/etc/nginx/certs/server.crt
      - ./certs/server.key:/etc/nginx/certs/server.key